language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements${TRAVIS_PYTHON_VERSION:0:1}.txt
  - pip install coveralls
script:
  - PYTHONPATH=. coverage run --source=comet --omit=*test_\*py $(which trial) comet
after_success:
  - coveralls
sudo: false
