language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - coverage run --source=comet --omit=*test_\*py $(which trial) comet
after_success:
  - coveralls
sudo: false
