language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install -r requirements${TRAVIS_PYTHON_VERSION:0:1}.txt
script:
  - PYTHONPATH=. $(which trial) comet
dist: xenial
